---
# tasks file for tomcat

- name: add tomcat user
  user:
    name: 'tomcat'

- name: copy tomcat to dest_path
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0775'
    owner: 'root'
    group: 'tomcat'
  loop:
    - src: 'tomcat/bin/'
      dest: '{{ tomcat.tomcat_home }}/bin'
    - src: 'tomcat/lib/'
      dest: '{{ tomcat.tomcat_home }}/lib'
    - src: 'tomcat/temp/'
      dest: '{{ tomcat.tomcat_home }}/temp'
    - src: 'tomcat/webapps/'
      dest: '{{ tomcat.tomcat_home }}/webapps'
    - src: 'conf/'
      dest: '{{ tomcat.tomcat_home }}/conf'
  notify: restart tomcat

- name: make sure tomcat default directory is created
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'root'
    group: 'tomcat'
    mode: '0775'
  loop:
    - '{{ tomcat.tomcat_home }}'
    - '{{ tomcat.tomcat_home }}/bin'
    - '{{ tomcat.tomcat_home }}/conf'
    - '{{ tomcat.tomcat_home }}/lib'
    - '{{ tomcat.tomcat_home }}/logs'
    - '{{ tomcat.tomcat_home }}/temp'
    - '{{ tomcat.tomcat_home }}/webapps'
    - '{{ tomcat.tomcat_home }}/work'

- name: add tomcat.service
  template:
    src: 'tomcat.service.j2'
    dest: '/usr/lib/systemd/system/{{ tomcat.service_name }}.service'
  notify: daemon reload

- name: enabled tomcat.service
  systemd:
    name: '{{ tomcat.service_name }}'
    enabled: 'yes'
