---
# tasks file for vminit

- name: remove default repo files
  file:
    path: '{{ item }}'
    state: 'absent'
  loop:
    - '/etc/yum.repos.d/CentOS-CR.repo'
    - '/etc/yum.repos.d/CentOS-Debuginfo.repo'
    - '/etc/yum.repos.d/CentOS-fasttrack.repo'
    - '/etc/yum.repos.d/CentOS-Media.repo'
    - '/etc/yum.repos.d/CentOS-Sources.repo'
    - '/etc/yum.repos.d/CentOS-Vault.repo'

- name: add centos repo
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0644'
  loop:
    - src: 'CentOS-Base.repo'
      dest: '/etc/yum.repos.d/CentOS-Base.repo'
    - src: 'epel.repo'
      dest: '/etc/yum.repos.d/epel.repo'

- name: update hostname at inventory hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: disable and stop firewalld
  systemd:
    name: 'firewalld'
    state: 'stopped'
    enabled: 'no'

- name: disable and stop selinux
  selinux:
    state: 'disabled'

- name: install some packages you need
  yum:
    name: '{{ item }}'
    state: 'present'
  loop: '{{ packages }}'
