---
# tasks file for pythonenv

- name: install pip
  yum:
    name: '{{ item }}'
    state: 'present'
  loop: '{{ _pythonenv_packages }}'

- name: create pip conf directory
  file:
    path: '~/.pip'
    state: 'directory'

- name: add aliyun pypi
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  loop:
    - src: 'pip.conf'
      dest: '~/.pip/pip.conf'

- name: install python packages
  shell: |
    pip3 install -U pip
    pip install {{ _pythonenv_pips }}
