---
# tasks file for clusterinit2

- shell:
    ls ~/.ssh/id_rsa
  register: rsa
  ignore_errors: True

- shell:
    ssh-keygen -f ~/.ssh/id_rsa -N ''
  when: rsa |failed


- slurp:
    src: ~/.ssh/id_rsa.pub
  register: monitoringsshkey

- authorized_key:
    user: root
    key: '{{ hostvars[item]["monitoringsshkey"]["content"] | b64decode }}'
  loop: '{{ vars.play_hosts }}'

- lineinfile:
    path: '/etc/hosts'
    line: '{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}'
  loop: '{{ vars.play_hosts }}'

- lineinfile:
    path: '~/.ssh/known_hosts'
    line: '{{ item }},{{ hostvars[item].ansible_default_ipv4.address }} ecdsa-sha2-nistp256 {{ hostvars[item].ansible_ssh_host_key_ecdsa_public }}'
    create: yes
  loop: '{{ vars.play_hosts }}'
