---
# tasks file for docce

- name: add docker-ce repo file
  copy:
    src: '{{ item }}.repo'
    dest: '/etc/yum.repos.d/{{ item }}.repo'
  loop: '{{ docce.repo_file }}'

- name: install docker-ce docker-compose
  yum:
    name: '{{ item }}'
    state: 'present'
  loop: '{{ docce.packages }}'

- name: enable and start docker service
  systemd:
    name: 'docker'
    state: 'started'
    enabled: 'yes'
