---
# tasks file for docce

- name: add docker-ce repo file
  get_url:
    url: '{{ _docce_repo }}'
    dest: '/etc/yum.repos.d/docker-ce.repo'
  when: internet is defined and internet |bool and _docce_repo is defined

- name: install docker-ce and docker-compose
  yum:
    name: '{{ item }}'
    state: 'latest'
    enablerepo: 'docker-ce-stable'
  loop:
    - 'docker-ce'
    - 'docker-compose'

- name: enable and start docker service
  systemd:
    name: 'docker'
    state: 'started'
    enabled: 'yes'
