---
# tasks file for docce

- name: add docker-ce repo file
  get_url:
    url: '{{ _docce_repo }}'
    dest: '/etc/yum.repos.d/docker-ce.repo'
  when: internet is defined and internet |bool and _docce_repo is defined

- name: install docker-ce and docker-compose
  yum:
    name: '{{ item }}'
    state: 'latest'
    enablerepo: 'docker-ce-stable'
  loop:
    - 'docker-ce-cli'
    - 'docker-ce'
    - 'docker-compose'

- name: add ali booster
  lineinfile:
    path: '/etc/docker/daemon.json'
    line: '{ "registry-mirrors": ["https://3bibh4vy.mirror.aliyuncs.com"] }'
    create: yes
  when: internet is defined and internet |bool

- name: enable and start docker service
  systemd:
    name: 'docker'
    state: 'started'
    enabled: 'yes'
