---
# tasks file for vminit

- name: remove default repo files
  file:
    path: '{{ item }}'
    state: 'absent'
  loop:
    - '/etc/yum.repos.d/CentOS-Base.repo'
    - '/etc/yum.repos.d/CentOS-CR.repo'
    - '/etc/yum.repos.d/CentOS-Debuginfo.repo'
    - '/etc/yum.repos.d/CentOS-fasttrack.repo'
    - '/etc/yum.repos.d/CentOS-Media.repo'
    - '/etc/yum.repos.d/CentOS-Sources.repo'
    - '/etc/yum.repos.d/CentOS-Vault.repo'

- name: add centos repo
  copy:
    src: '{{ item }}.repo'
    dest: '/etc/yum.repos.d/{{ item }}.repo'
    mode: '0644'
  loop: '{{ vminit.repo_file }}'
  when: vminit.repo_file is defined

- name: get centos repo
  get_url:
    url: '{{ item.url }}'
    dest: '/etc/yum.repos.d/{{ item.name }}.repo'
  loop: '{{ vminit.repo_url }}'
  when: vminit.repo_url is defined

- name: update hostname at inventory hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: disable and stop firewalld
  systemd:
    name: 'firewalld'
    state: 'stopped'
    enabled: 'no'

- name: disable and stop selinux
  selinux:
    state: 'disabled'

- name: upgrade all
  yum:
    name: '*'
    state: 'latest'
    update_only: 'yes'
  when: vminit.upgrade is defined and vminit.upgrade |bool

- name: install some packages you need
  yum:
    name: '{{ item }}'
    state: 'present'
  loop: '{{ vminit.packages }}'
  when: vminit.packages is defined
