---
# tasks file for appconf

- name: copy war to webapps and restart tomcat
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0775'
    owner: 'root'
    group: 'tomcat'
  loop: '{{ wars }}'
  notify: restart tomcat
