---
# tasks file for appconf

- name: copy war to webapps and restart tomcat
  copy:
    src: '{{ item }}.war'
    dest: '{{ tomcat_home }}/webapps/{{ item }}.war'
    mode: '0775'
    owner: 'root'
    group: 'tomcat'
  loop: '{{ wars }}'
  notify: restart tomcat
