---
# tasks file for java

- name: Extract {{ java.src }} into {{ java.dest }}
  unarchive:
    src: '{{ java.src }}'
    dest: '{{ java.dest }}'
  when: java.src is defined

- block:
    
    - name: get_url {{ java.repo_url }} into {{ java.dest }}
      get_url:
        url: '{{ java.repo_url }}'
        dest: '/tmp/{{ java.name }}'

    - name: Extract {{ java.name }}
      unarchive:
        src: '/tmp/{{ java.name }}'
        dest: '{{ java.dest }}'
        remote_src: yes

  when: java.repo_url is defined and java.name is defined

- name: add {{ java.dest }}{{ java.dirname }}/bin into $PATH
  lineinfile:
    path: '/etc/bashrc'
    line: 'export PATH=$PATH:{{ java.dest }}{{ java.dirname }}/bin'
    create: 'yes'

- name: add JAVA_HOME={{ java.dest }}{{ java.dirname }}
  lineinfile:
    path: '/etc/bashrc'
    line: 'export JAVA_HOME={{ java.dest }}{{ java.dirname }}'
    create: 'yes'
