---
# tasks file for java

- name: copy java directory to dest_path
  copy:
    src: 'java/'
    dest: '{{ java.java_home }}'
    mode: '0755'
  when: java.check_java |bool

- name:
  lineinfile:
    path: '/etc/bashrc'
    line: 'export PATH=$PATH:{{ java.java_home }}'
    create: 'yes'
