---
# tasks file for java

- name: Extract {{ java.src }} into {{ java.dest }}
  unarchive:
    src: '{{ java.src }}'
    dest: '{{ java.dest }}'

- name: add {{ java.dest }}{{ java.dirname }}/bin into $PATH
  lineinfile:
    path: '/etc/bashrc'
    line: 'export PATH=$PATH:{{ java.dest }}{{ java.dirname }}/bin'
    create: 'yes'

- name: add JAVA_HOME={{ java.dest }}{{ java.dirname }}
  lineinfile:
    path: '/etc/bashrc'
    line: 'export JAVA_HOME={{ java.dest }}{{ java.dirname }}'
    create: 'yes'
