---
# tasks file for java
- block:
    - name: Extract {{ _java_local_src }} into {{ _java_dest }}
      unarchive:
        src: '{{ _java_local_src }}'
        dest: '{{ _java_dest }}'
      when: local is defined and local|bool and _java_local_src is defined
    
    - block:
        
        - name: get_url {{ _java_repo_url }} into {{ _java_dest }}
          get_url:
            url: '{{ _java_repo_url }}'
            dest: '/tmp/{{ _java_name }}'
    
        - name: Extract {{ _java_repo_name }}
          unarchive:
            src: '/tmp/{{ _java_repo_name }}'
            dest: '{{ _java_dest }}'
            remote_src: yes
    
      when: _java_repo_url is defined
    
    - name: add {{ _java_dest }}{{ _java_dirname }}/bin into $PATH
      lineinfile:
        path: '/etc/bashrc'
        line: 'export PATH=$PATH:{{ _java_dest }}{{ _java_dirname }}/bin'
        create: 'yes'
    
    - name: add JAVA_HOME={{ _java_dest }}{{ _java_dirname }}
      lineinfile:
        path: '/etc/bashrc'
        line: 'export JAVA_HOME={{ _java_dest }}{{ _java_dirname }}'
        create: 'yes'
  when: _java_oracle is defined and _java_oracle|bool

- name: yum install java
  yum:
    name: 'java'
    state: 'latest' 
  when: not ( _java_oracle is defined and _java_oracle|bool )
