---
# tasks file for mysql

- debug:
    msg: '{{ mysql }}'

- copy:
    src: '{{ item }}.repo'
    dest: '/etc/yum.repos.d/{{ item }}.repo'
  loop: '{{ mysql.repo_file }}'

- yum:
    name: '{{ item }}'
    state: 'latest'
    enablerepo: '{{ mysql.repoid }}'
  loop: '{{ mysql.repo_rpm }}'

- systemd:
    name: 'mysqld'
    state: 'started'
    enabled: yes

- template:
    src: 'mysql.sh.j2'
    dest: '/tmp/mysql.sh'

- shell: |
    bash /tmp/mysql.sh
  register: passwd

- debug:
    msg: '{{ passwd }}'

