---
# tasks file for mysql

- copy:
    src: '{{ item }}.repo'
    dest: '/etc/yum.repos.d/{{ item }}.repo'
  loop: '{{ _mysql_repo_file }}'
  when: internet is defined and internet|bool and _mysql_repo_file is defined

- yum:
    name: '{{ item }}'
    state: 'latest'
    enablerepo: '{% if internet %}{{ _mysql_repoid_i }}{% else %}{{ _mysql_repoid }}{% endif %}'
  loop: '{{ _mysql_repo_rpm }}'

- lineinfile:
    path: '/etc/my.cnf'
    line: '{{ item }}'
  loop: '{{ _mysql_my_cnf }}'

- systemd:
    name: 'mysqld'
    state: 'restarted'
    enabled: yes

- template:
    src: 'mysql.sh.j2'
    dest: '/tmp/mysql.sh'

- shell: |
    bash /tmp/mysql.sh
  register: passwd

- debug:
    msg: '{{ passwd }}'

