---
# tasks file for hive

- block:
    - name: get_url {% if internet %}{{ _hive_repo_url_i }}{% else %}{{ _hive_repo_url }}{% endif %}
      get_url:
        url: '{% if internet %}{{ _hive_repo_url_i }}{% else %}{{ _hive_repo_url }}{% endif %}'
        dest: '/tmp/{{ _hive_repo_name }}'

    - name: 'Extract /tmp/{{ _hive_repo_name }}'
      unarchive:
        src: '/tmp/{{ _hive_repo_name }}'
        dest: '{{ _hive_dest }}'
        remote_src: yes

  when: _hive_repo_url is defined and _hive_repo_url_i is defined

- name: install connector
  yum:
    name: 'mysql-connector-java.noarch'
    state: 'latest'

- name: hive conf
  template:
    src: '{{ item }}.j2'
    dest: '{{ _hive_dest }}/{{ _hive_dirname }}/conf/{{ item }}'
  loop: '{{ _hive_conf }}'

- name: add connector
  copy:
    src: '/usr/share/java/mysql-connector-java.jar'
    dest: '{{ _hive_dest }}/{{ _hive_dirname }}/lib/'
    remote_src: yes

- name: add {{ _hive_dest }}/{{ _hive_dirname }}/bin into $PATH
  lineinfile:
    path: '/etc/bashrc'
    line: 'export PATH=$PATH:/{{ _hive_dest }}/{{ _hive_dirname }}/bin'
    create: yes

- name: set HIVE_HOME {{ _hive_dest }}/{{ _hive_dirname }}
  lineinfile:
    path: '/etc/bashrc'
    line: 'export HIVE_HOME={{ _hive_dest }}/{{ _hive_dirname }}'
    create: yes

- name: cp start-hive.sh
  copy:
    src: 'start-hive.sh'
    dest: '{{ _hive_dest }}/{{ _hive_dirname }}/bin/'
    mode: '0755'
