- name: reposync
  gather_facts: no
  hosts: reposync
  tasks:
    - name: copy yum repo
      copy:
        src: './centos-reposync.repo'
        dest: '/etc/yum.repos.d/centos-reposync.repo'

    - name: install package
      package:
        name: '{{ item }}'
        state: present
      loop:
        - "yum-utils"

    - name: check dir
      file:
        path: '{{ item }}'
        state: directory
      loop:
        - "/root/centos/6"
        - "/root/centos/7"

    - name: reposync
      shell: |
        reposync -r base6 -r updates6 -r extras6 -r epel6 -p /root/centos/6/;
        reposync -r base7 -r updates7 -r extras7 -r epel7 -p /root/centos/7/;
