---
# tasks file for tomcat

- name: add tomcat user
  user:
    name: 'tomcat'

- name: copy tomcat to dest_path
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0775'
    owner: 'root'
    group: 'tomcat'
  loop:
    - src: 'tomcat/bin/'
      dest: '{{ TOMCAT_HOME }}/bin'
    - src: 'tomcat/lib/'
      dest: '{{ TOMCAT_HOME }}/lib'
    - src: 'tomcat/temp/'
      dest: '{{ TOMCAT_HOME }}/temp'
    - src: 'tomcat/webapps/'
      dest: '{{ TOMCAT_HOME }}/webapps'
    - src: 'conf/'
      dest: '{{ TOMCAT_HOME }}/conf'
  notify: restart tomcat

- name: make sure tomcat default directory is created
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'root'
    group: 'tomcat'
    mode: '0775'
  loop:
    - '{{ TOMCAT_HOME }}'
    - '{{ TOMCAT_HOME }}/bin'
    - '{{ TOMCAT_HOME }}/conf'
    - '{{ TOMCAT_HOME }}/lib'
    - '{{ TOMCAT_HOME }}/logs'
    - '{{ TOMCAT_HOME }}/temp'
    - '{{ TOMCAT_HOME }}/webapps'
    - '{{ TOMCAT_HOME }}/work'

- name: add tomcat.service
  template:
    src: 'tomcat.service.j2'
    dest: '/usr/lib/systemd/system/{{ SERVICE_NAME }}.service'
  notify: daemon reload
