---
# tasks file for redis

- get_url:
<<<<<<< HEAD
    url: '{{ redis.repo_url }}'
    dest: '/tmp/{{ redis.name }}'

- unarchive:
    src: '/tmp/{{ redis.name }}'
=======
    url: 'http://download.redis.io/redis-stable.tar.gz'
    dest: '/tmp/redis-stable.tar.gz'

- unarchive:
    src: '/tmp/redis-stable.tar.gz'
>>>>>>> 3a91860abc2a5d2eb6ee61e6a44335a717d0e133
    dest: '{{ redis.dest }}'
    remote_src: yes

- shell: |
    cd {{ redis.dest }}/{{ redis.dirname }};
    make;
    make install;
  register: make_result

- debug:
    msg: '{{ make_result }}'

- file:
    path: '{{ item }}'
    state: 'directory'
  loop:
    - '/etc/redis'
    - '/var/lib/redis'

- copy:
    src: '{{ redis.dest }}/{{ redis.dirname }}/redis.conf'
    dest: '/etc/redis/6379.conf'
    remote_src: yes

- replace:
    path: '/etc/redis/6379.conf'
    regexp: '^# requirepass .*'
    replace: 'requirepass {{ redis.passwd }}'

- replace:
    path: '/etc/redis/6379.conf'
    regexp: 'daemonize.*'
    replace: 'daemonize yes'

- replace:
    path: '/etc/redis/6379.conf'
    regexp: '^dir.*'
    replace: 'dir /var/lib/redis'

- lineinfile:
    path: '/etc/bashrc'
    line: 'alias redis-server="redis-server /etc/redis/6379.conf"'
    create: yes
