---
# tasks file for git

- name: Extract {{ _git_local_src }} into {{ _git_dest }}
  unarchive:
    src: '{{ _git_local_src }}'
    dest: '{{ _git_dest }}'
  when: local is defined and local|bool and _git_local_src is defined

- block:
    - name: get_url {% if internet %}{{ _git_repo_url_i }}{% else %}{{ _git_repo_url }}{% endif %} into /tmp
      get_url:
        url: '{% if internet %}{{ _git_repo_url_i }}{% else %}{{ _git_repo_url }}{% endif %}'
        dest: '/tmp/{{ _git_repo_name }}'

    - name: Extract {{ _git_repo_name }}
      unarchive:
        src: '/tmp/{{ _git_repo_name }}'
        dest: '{{ _git_dest }}'
        remote_src: yes

  when: _git_repo_url_i is defined and _git_repo_url is defined

- name: build 
  shell: |
    cd {{ _git_dest }}{{ _git_dirname }};
    ./configure --with-curl;
    make;
    make install;

- name: source git completion
  lineinfile:
    path: '/etc/bashrc'
    line: '. {{ _git_dest }}{{ _git_dirname }}/contrib/completion/git-completion.bash'
    state: 'present'
